spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crspngdb
    driver-class-name: org.postgresql.Driver
    username: foo
    password: Munich123$
    dbcp:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  application:
    name: Toll Processor
logging:
  level: debug